services:
  postgres:
    image: postgres:15
    container_name: prenota-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prenotadb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
